version: '3'

services:
  app:
    image: lobre/notion-proxy
    container_name: domain-proxy
    ports:
      - 80:80
    environment:
      - HOST=example.com
      - PROTO=http
      - REDIRECT=What-s-New-157765353f2c4705bd45474e5ba8b46c
